// utils/roles.ts
export const ROLES = {
  ADMIN: "ADMIN",
  CHEF: "CHEF_DEPARTEMENT",
  ENSEIGNANT: "ENSEIGNANT",
  RESPONSABLE: "RESPONSABLE_RESOURCE",
  FOURNISSEUR: "FOURNISSEUR",
  TECHNICIEN: "TECHNICIEN",
};
